#!/bin/sh

if which fourmolu > /dev/null ; then
  fourmolu --mode check sel libsodium-bindings
else
  echo "Fourmolu not found, aborting."
  exit 1
fi

if which hlint > /dev/null ; then
  hlint src libsodium-bindings
else
  echo "HLint not found, aborting."
  exit 1
fi
