#!/bin/sh

haskell_files=$(find src -name "*.hs")

if which ormolu > /dev/null ; then
  for f in ${haskell_files}; do
    if ! ormolu -m 'check' "$f" 1> /dev/null 2> /dev/null ; then 
      echo "$f is not formatted, aborting."
      exit 1
    fi
  done
  if ! ormolu -m 'check' 'Setup.hs' 1> /dev/null 2> /dev/null ; then
    echo "Setup.hs is not formatted, aborting."
    exit 1
  fi
else
  echo "Ormolu not found, aborting."
  exit 1
fi

if which hlint > /dev/null ; then
  for f in ${haskell_files}; do
    if ! hlint -h '.hlint.yaml' -q "$f" ; then
      exit 1
    fi
  done
else
  echo "HLint not found, aborting."
  exit 1
fi

if which cabal-fmt > /dev/null ; then
  if ! cabal-fmt -c "cryptography-libsodium-bindings.cabal" ; then
    exit 1
  fi
else
  echo "cabal-fmt not found, aborting."
  exit 1
fi
