#!/bin/sh

if which fourmolu > /dev/null ; then
  make style
else
  echo "Ormolu not found, aborting."
  exit 1
fi

if which hlint > /dev/null ; then
  make lint
else
  echo "HLint not found, aborting."
  exit 1
fi
